### ISSUE TITLE
Does subhub return 500s if it can't connect to AWS or Stripe?

### ISSUE THREAD

**Issue by 6a68** [mozilla/subhub#170]
If subhub can't connect to Stripe or AWS for any reason, Subscription and Customer API calls will fail. Will 500 errors be returned in that case? It would be good to document this in the swagger/openapi spec.

**Comment by marty331** [comment]
@6a68 we'll have this added to our sprint which starts on 7/31/19.

**Comment by marty331** [comment]
@6a68 this has been addressed in PR: https://github.com/mozilla/subhub/pull/183  I just pushed a new build to dev, please review and close this issue if you are satisfied with the results.

**Comment by marty331** [comment]
Issue resolved, closing.
