### ISSUE TITLE
GET /v1/customer/:uid/subscriptions responds with object, YAML specifies an array

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#178]
In using `GET /v1/customer/:uid/subscriptions`, we ran into this:

* In the swagger YAML, the response is specified [as `Subscriptions`](https://github.com/mozilla/subhub/blob/master/subhub/swagger.yaml#L121), described as [type array](https://github.com/mozilla/subhub/blob/master/subhub/swagger.yaml#L461)

* [As implemented](https://github.com/mozilla/subhub/blob/master/subhub/sub/payments.py#L195), the response is an object `{ subscriptions: [] }` rather than a bare array.

We're rolling out a fix on the FxA side to account for the current implementation, so it's probably best to leave that as-is and update the YAML.

**Comment by marty331** [comment]
Closing, will pick up #205 for spec compliance.
