### ISSUE TITLE
Use proper List typing

### ISSUE THREAD

**Issue by bbangert** [mozilla/subhub#197]
Multiple functions throughout subhub use `list` as the type for a parameter or result. They should however be using the `typing` modules `List` with the type of list it is:
https://docs.python.org/3/library/typing.html#type-aliases

For example, one function returns a list of subscriptions, which should be written as:
```python
from typing import List

def somefunc(...args) -> List[stripe.Subscription]:
    ....
```

mypy and PyCharm will then work correctly with the type information.

**Comment by marty331** [comment]
Resolved with #228
