### ISSUE TITLE
Remove unnecessary source file headers

### ISSUE THREAD

**Issue by bbangert** [mozilla/subhub#198]
All of the Python files have had headers inserted that are unnecessary or odd to include. The first one:
```#!/usr/bin/env python3```

Is used for running a Python file as a script, and Python library source files shouldn't have this added as they're not directly executed as a script.

The second:
```# -*- coding: utf-8 -*-```

is used when including unicode characters in a Python 2 source file. SubHub is entirely Python 3, which is unicode by default so this shouldn't be included.

**Comment by sidler-mozilla** [comment]
This should be handled with the above merged PR.  Please close if you agree.
