### ISSUE TITLE
Clean up and fix code around find newest subscription

### ISSUE THREAD

**Issue by bbangert** [mozilla/subhub#203]
The `find_newest_subscription` [function in payments.py](https://github.com/mozilla/subhub/blob/master/subhub/sub/payments.py#L48) is missing a return type annotation. It would've helped in this case to catch a failed expectation. The function on its own is capable of returning `None` (if subscriptions is empty), or a dict with a `data` key.

At the moment, there's only a single calling context, that typically guarantees there will be at least one subscription (as it creates one), but if it is not created, then the function would return `None`. This is a problem because the caller of the function proceeds with the assumption that the call will *always return* a dict with a `data` key which is used by `create_return_data`. `create_return_data` requires a dict to be passed in with a `data` key or it will throw a KeyError.

In the future, to make some of these errors less likely, there's a [TypedDict PEP](https://www.python.org/dev/peps/pep-0589/) which would be used to ensure this isn't done.

Alternatively, the `find_newest_subscription` function could just return a list of subscriptions, and it would be empty in the event there is none. The `create_return_data` could then be updated to not use a `data` key in a dict.

**Comment by bbangert** [comment]
One other note, in theory its questionable why this function is even needed as it increases Stripe API calls, and the prior call to Subscription.create should return all the data needed already.

**Comment by marty331** [comment]
Resolved.
