### ISSUE TITLE
Support tickets are submitted under the wrong branding

### ISSUE THREAD

**Issue by bsurd** [mozilla/subhub#224]
#### Affected versions:
- Firefox 68.0.2

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
Have a account with an active subscription.

#### Steps to reproduce
1. Go to [Firefox Accounts](https://accounts.stage.mozaws.net/settings).
2. In the "Subscriptions" section click on "Manage" and then on "Contact Support" from the next page.
3. Complete all of the fields and file a support ticket.
4. Open the previously filled ticket in [Zendesk](https://mozilladev.zendesk.com/agent/filters/360094062071) and check the brand in the left side panel.

#### Expected result:
The brand is displayed as "Premium Services".

#### Actual result:
The brand is displayed as "Mozilla Enterprise".

#### Notes:
The issue is reproducible for any of the support categories. 

![1](https://user-images.githubusercontent.com/17178945/63598966-49470400-c5c9-11e9-9ac8-7e302a08238c.gif)

**Comment by stlhood** [comment]
This may also relate to COPS-758.

**Comment by mozbrandon** [comment]
@stlhood upcoming fix will also resolve COPS-795.

**Comment by mozbrandon** [comment]
This has been resolved by updating a trigger in Zendesk to associate the correct brand; I can see tickets flowing in correctly now. 

Trigger https://mozilladev.zendesk.com/agent/admin/triggers/360093685212

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on [FPN-stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/) site, using the latest Firefox Release (70.0.1), Beta (71.0b5) and Nightly (72.0a1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
