### ISSUE TITLE
After we moved all tests to mocks, STRIPE_API_KEY still required

### ISSUE THREAD

**Issue by sidler-mozilla** [mozilla/subhub#237]
After moving all of our tests to mocks, our code still requires the STRIPE_API_KEY to run out tests.  Fix this and remove this dependency.  Once it has been removed, communicate that the doit task that checks for the value can be removed to the SRE.

**Comment by marty331** [comment]
Current tests that fail without STRIPE_API_KEY:

src/sub/tests/unit/test_payment_calls.py:
- test_subscribe_customer_existing

src/sub/tests/unit/test_subhub.py:
- test_subscribe_customer_existing

**Comment by jackiemunroe** [comment]
https://jira.mozilla.com/browse/COPS-739

**Comment by jackiemunroe** [comment]
This has been resolved.
