### ISSUE TITLE
Email: Payment received has bad link to update preferences

### ISSUE THREAD

**Issue by rlr** [mozilla/subhub#293]
This was filed over in the guardian website repo by @rbillings.

> Payment received email [Sandbox: Firefox Guardian (Monthly) monthly payment received] includes a bad link to update your email preferences. The link goes to:
> https://www.mozilla.org/newsletter/existing/%%Token__c%%/

**Comment by marty331** [comment]
@desiree-mofo Can you look at this?

**Comment by stlhood** [comment]
Confirmed, this can be closed.
