### ISSUE TITLE
Email: Suggest removing duplicate "monthly" from title

### ISSUE THREAD

**Issue by rlr** [mozilla/subhub#294]
This was filed over in the guardian website repo by @rbillings. I'm guessing this is a simple configuration update on the product name?

> The email for payment received has this title:
> Sandbox: Firefox Guardian (Monthly) monthly payment received
> 
> Suggest removing the second "monthly" or changing the title of the product to remove "Monthly".

**Comment by marty331** [comment]
@desiree-mofo Just tagging you as this is email related.

**Comment by desiree-mofo** [comment]
The first Monthly is actually part of the product name that was set up in Stripe. If product names will have a frequency (monthly, yearly, etc) - then we should update the title. I will defer to the product managers on how the products will be set up in Stripe before amending the Subject line verbiage

**Comment by stlhood** [comment]
I've updated the email spec to remove "monthly" from the subject line.

**Comment by desiree-mofo** [comment]
Updated the subject line for the recurring emails to remove "Monthly" per the email specification document. New subject line reads "%%serviceName%% Payment Received" (Service name will be populated w/ the product they purchased)

**Comment by stlhood** [comment]
Confirmed, this issue can be closed.
