### ISSUE TITLE
(Subscriptions Payments) Email: Thank you went into Spam

### ISSUE THREAD

**Issue by rlr** [mozilla/subhub#295]
This was filed over in the guardian website repo by @rbillings.

> After signing up for Guardian, the Thank You for Subscribing email went directly into my Spam folder [although the payment one went through]. Not sure if there's a way to avoid this, but I wouldn't have seen it as a user.

**Comment by marty331** [comment]
@desiree-mofo another email related issue, is there a SF setting to keep emails from getting dumped to spam?

**Comment by desiree-mofo** [comment]
For testing, the emails are being sent from Sales Cloud - once we move to Production, the emails will be sent from Marketing cloud, which has better deliverability than Sales Cloud environments. Our marketing cloud domain is managed and monitored in terms of deliverability, this is why Marketing cloud was chosen as the platform to send the emails. We do not have a Marketing Cloud environment available to us for testing, so for end to end testing we needed to temporarily use Sales Cloud

**Comment by marty331** [comment]
Known issue with SF dev, will resolve in prod.
