### ISSUE TITLE
Cancel cancels immediately vs. at the end of the period.

### ISSUE THREAD

**Issue by marty331** [mozilla/subhub#33]
Cancellation of subscription should be at the end of the existing period.  Also should not delete subscription.

**Comment by lmorchard** [comment]
Another part of this, maybe for a follow up issue: We should probably have an API to [undo the cancellation](https://stripe.com/docs/billing/subscriptions/canceling-pausing#reactivating-canceled-subscriptions). "Resubscribe" is [a button in our UX wireframes](https://mozilla.invisionapp.com/share/K2RBDY3VU9X#/screens/360130692), which I think we were going to re-phrase as "Reactivate".

**Comment by marty331** [comment]
This was resolved in Jira SS-95.
