### ISSUE TITLE
Error while attempting to retrieve_stripe_customer using a charge ID

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#332]
While working to troubleshoot [an issue adjacent to zip code validation](https://github.com/mozilla/fxa/issues/3152), I noticed that subhub was logging this error while attempting to fetch customer data:
```
{"message": "RETRIEVE STRIPE CUSTOMER ERROR", "lineno": 168, "pathname": "/subhub/sub/shared/vendor.py", "levelname": "ERROR", "threadName": "Thread-31", "error": "Request req_fF3sb9JkiNGkbd: No such customer: ch_1FYh1KEOSeHhIAfQY32wfWhV", "logger": "__main__", "timestamp": "2019-10-28T23:26:25.579941Z"}
```
The `ch_` prefix on `ch_1FYh1KEOSeHhIAfQY32wfWhV` looks like it's a Charge ID and not a Customer ID.

Digging around, I noticed [this line in `create_update_data` in `src/sub/payments.py`](https://github.com/mozilla/subhub/blob/master/src/sub/payments.py#L549):
```python
intents = vendor.retrieve_stripe_customer(invoice["charge"])
```
Seems like this should be more like [this line](https://github.com/mozilla/subhub/blob/master/src/sub/payments.py#L399)?
```python
intents = vendor.retrieve_stripe_charge(invoice["charge"])
```

**Comment by marty331** [comment]
Thanks @lmorchard, you are correct about this.  The fix will be out in the next PR.

**Comment by marty331** [comment]
PR for has been pushed to prod and prod-test @lmorchard
