### ISSUE TITLE
Subscription cancelation email is not sent

### ISSUE THREAD

**Issue by madalincm** [mozilla/subhub#335]
#### Affected versions:
- Firefox Release 70.0

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.2

#### Precondition
User has an active subscription

#### Steps to reproduce
1. Open the manage subscription page and cancel the subscription
2. Observe the received emails

#### Expected result:
- Subscription cancelation email is sent

#### Actual result:
- Subscription cancelation email is not sent

#### Notes:
- Reproduced using the following email address: mcotetiu+test52@mozilla.com

**Comment by desiree-mofo** [comment]
I see the contact and an initial purchase record in the Salesforce sandbox, but nothing for a cancellation. @marty331  or @jackiemunroe  - could you check on a cancellation message for subscription id: sub_G50eb6T8lYmMaW

**Comment by stlhood** [comment]
@jackiemunroe reports that she has found the underlying bug and it will be fixed this Thursday.

**Comment by jackiemunroe** [comment]
Resolved with https://github.com/mozilla/subhub/pull/337

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible, using the latest Firefox Release (70.0.1), Beta (71.0b5) and Nightly (72.0a1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
