### ISSUE TITLE
Reactivation of cancelled subscription email is not sent

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/subhub#336]
#### Affected versions:
- Firefox Release 70.0
- Firefox Beta 71.0b4
- Firefox Nightly 72.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.15
- Linux Ubuntu 16.04 (64-bit)

#### Prerequisites:
Have an active subscription.

#### Steps to reproduce
1. Go to [Subscription settings](https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions) and Cancel your subscription.
2. Reactivate the cancelled subscription.

#### Expected result:
A mail is sent, informing the user about the resubscription.

#### Actual result:
The mail is not sent.

#### Notes:
I used this email for subscribing: ljanos+20191029@mozilla.com.

**Comment by jackiemunroe** [comment]
Related to: https://github.com/mozilla/subhub/issues/305

**Comment by stlhood** [comment]
COPS-786 is complete and closed. This new email is now being fired.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible, using the latest Firefox Release (70.0.1). Verified on Windows 10 x64, Mac 10.14.2 and Linux Ubuntu 16.04 x64.
