### ISSUE TITLE
Capitalize CC brand name on emails

### ISSUE THREAD

**Issue by johngruen** [mozilla/subhub#366]

**Comment by stlhood** [comment]
In our receipt emails, the payment method is being shown in all lower-case (e.g. "visa" instead if "VISA", "amex" instead of "AMEX").

![image](https://user-images.githubusercontent.com/42821/68793081-6bb55000-0601-11ea-9307-c28de3a6bbed.png)

Tracked as COPS-894.

**Comment by imskr** [comment]
Can I work on this

**Comment by marty331** [comment]
@imskr Thank you for the offer but I believe we have resolved this issue already.

**Comment by imskr** [comment]
No problem @marty331

**Comment by marty331** [comment]
Already resolved.
