### ISSUE TITLE
Verify Next Billing Cycle dates on Emails

### ISSUE THREAD

**Issue by johngruen** [mozilla/subhub#367]

**Comment by marty331** [comment]
@johngruen Have you experienced getting an email with an incorrect billing cycle date?

**Comment by stlhood** [comment]
The "last day of service" in the subscription cancellation email is incorrect. Additionally, the "date of next invoice" in the new subscription and payment receipt emails is incorrect. These are both due to an issue with the Stripe fields we're passing along.

Tracked as COPS-895.

**Comment by stlhood** [comment]
This issue has been resolved and the fix is live in production.
