### ISSUE TITLE
Allow multiple subhub API keys active for easier API key rotation

### ISSUE THREAD

**Issue by jbuck** [mozilla/subhub#411]
We had to rotate the subhub API key today, and it required synchronous coordination between the FxA & Subhub teams and also resulted in a few minutes downtime while FxA and subhub are deploying with the new API key.

It would be nice if multiple subhub API keys were supported so that you could do something like

1. Subhub generates new API key, deploys with old and new API key active
2. FxA deploys with new API key
3. Subhub deploys only with new API key

That way we could take our time doing API key rotations, and also have no downtime.

**Comment by marty331** [comment]
Will not fix due to Arch2.0 adoption.
