### ISSUE TITLE
Thank you for subscribing mail "card ending" missing

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/subhub#449]
#### Affected versions:
- All Firefox.

#### Affected Platforms:
- All Windows.
- All Mac.
- All Linux.

#### Prerequisites:
Setup instructions before continuing with the steps.

#### Steps to reproduce
1. Make a subscription for Guardian VPN.
2. Open your inbox and check the invoice.

#### Expected result:
The charge information is reading "Charged to Visa card ending ##".

#### Actual result:
The charge information is reading "Charged to visa #".

![Screenshot (78)](https://user-images.githubusercontent.com/48829350/72995400-80804200-3e01-11ea-8078-7b1ee34a6bb3.png)

**Comment by mozbrandon** [comment]
Disregard, this is not a production issue, these emails are not being sent to by SFMC. The expected design is out of date also.
