### ISSUE TITLE
API: Add method to determine if source on file needs updating

### ISSUE THREAD

**Issue by bbangert** [mozilla/subhub#45]
There's no apparent API endpoint at the moment to determine if a customer's source needs to be updated. Either the existing API call to return customer information with payment status should be updated, or a new endpoint that can indicate if the payment source needs updating.

This is used by FxA Account Management to indicate to a user that they must update their payment data.

**Comment by marty331** [comment]
@bbangert We will only be notified of this via a webhook event.  Do you want to have this event processed and sent to FxA?

Event:
customer.source.expiring
Description:
Occurs whenever a card or source will expire at the end of the month.

Otherwise, we already include the Exp Month and Year for the default source in the current API.

**Comment by bbangert** [comment]
Hmm, I think we can avoid receiving that event in this case. I was thinking that if a card is nuked entirely, and Stripe is aware that its no longer a valid card (stolen, etc), then we'd need a way to indicate that we couldn't process the card.

So to rephrase perhaps. Lets say its not an expiration issue, but the card couldn't get charged at all. Does the subscription info API call indicate errors with a source on file so that it can be shown as needing an update?

**Comment by bbangert** [comment]
The FxA bug referenced here lists another Stripe event 'invoice.payment_action_required' which will also need to be fed into the SQS queue for FxA Auth.

**Comment by lmorchard** [comment]
Just mentioned [over here](https://github.com/mozilla/fxa/issues/970#issuecomment-492834057): this might be good info to include in the `GET /customer/{uid}` resource, since we'll query it anyway to get payment info for display.

**Comment by marty331** [comment]
@bbangert @lmorchard SubHub will get the status of the subscription when it's either created or when a new period starts.  SubHub will not get the exact reason if a payment is declined in the customer_update function.  However, there is an event that is fired called payment_intent.payment_failed that will provide details about the payment failing - see below redacted example
`{
  "object": {
    "id": "pi_xxxx",
    "object": "payment_intent",
    "amount": 1000,
    "amount_capturable": 0,
    "amount_received": 0,
    "application": null,
    "application_fee_amount": null,
    "canceled_at": null,
    "cancellation_reason": null,
    "capture_method": "automatic",
    "charges": {
      "object": "list",
      "data": [
        {
          "id": "ch_xxxx",
          "object": "charge",
          "amount": 1000,
          "amount_refunded": 0,
          "application": null,
          "application_fee": null,
          "application_fee_amount": null,
          "balance_transaction": null,
          "billing_details": {
            "address": {
              "city": null,
              "country": null,
              "line1": null,
              "line2": null,
              "postal_code": "22222",
              "state": null
            },
            "email": null,
            "name": null,
            "phone": null
          },
          "captured": false,
          "created": 1558035313,
          "currency": "usd",
          "customer": "cus_xxx",
          "description": "Payment for invoice 1D1C1268-0002",
          "destination": null,
          "dispute": null,
          "failure_code": "card_declined",
          "failure_message": "Your card was declined.",
          "fraud_details": {
            "stripe_report": "fraudulent"
          },
          "invoice": "in_xxx",
          "livemode": false,
          "metadata": {
          },
          "on_behalf_of": null,
          "order": null,
          "outcome": {
            "network_status": "not_sent_to_network",
            "reason": "merchant_blacklist",
            "risk_level": "highest",
            "risk_score": 89,
            "seller_message": "Stripe blocked this payment.",
            "type": "blocked"
          },
          "paid": false,
          "payment_intent": "pi_xxx",
          "payment_method": "src_xxx",
          "payment_method_details": {
            "card": {
              "brand": "visa",
              "checks": {
                "address_line1_check": null,
                "address_postal_code_check": "pass",
                "cvc_check": "pass"
              },
              "country": "US",
              "description": null,
              "exp_month": 12,
              "exp_year": 2023,
              "fingerprint": "bxxx",
              "funding": "credit",
              "last4": "0019",
              "three_d_secure": {
                "authenticated": false,
                "succeeded": true,
                "version": "1.0"
              },
              "wallet": null
            },
            "type": "card"
          },
          "receipt_email": null,
          "receipt_number": null,
          "receipt_url": "https://pay.stripe.com/receipts/acct_xxxl",
          "refunded": false,
          "refunds": {
            "object": "list",
            "data": [
            ],
            "has_more": false,
            "total_count": 0,
            "url": "/v1/charges/ch_xxx/refunds"
          },
          "review": null,
          "shipping": null,
          "source": {
            "id": "src_xxx",
            "object": "source",
            "amount": 1000,
            "client_secret": "src_client_secret_xxx",
            "created": 1558035313,
            "currency": "usd",
            "flow": "redirect",
            "redirect": {
              "failure_reason": null,
              "return_url": "stripejs://use_stripe_sdk/return_url",
              "status": "not_required",
              "url": "https://hooks.stripe.com/redirect/authenticate/src_xxxxxn?client_secret=src_client_secret_xxxx"
            },
            "statement_descriptor": null,
            "status": "consumed",
            "three_d_secure": {
              "card": "src_xxxx",
              "exp_month": 12,
              "exp_year": 2023,
              "last4": "0019",
              "country": "US",
              "brand": "Visa",
              "address_zip_check": "unavailable",
              "cvc_check": "unavailable",
              "funding": "credit",
              "fingerprint": "bMxxx",
              "three_d_secure": "optional",
              "customer": null,
              "authenticated": false,
              "name": null,
              "address_line1_check": null,
              "tokenization_method": null,
              "dynamic_last4": null
            },
            "type": "three_d_secure",
            "usage": "single_use"
          },
          "source_transfer": null,
          "statement_descriptor": null,
          "status": "failed",
          "transfer_data": null,
          "transfer_group": null
        }
      ],
      "has_more": true,
      "total_count": 2,
      "url": "/v1/charges?payment_intent=pi_xxxxx"
    },
    "client_secret": "pi_xxxxxx",
    "confirmation_method": "automatic",
    "created": 1558033577,
    "currency": "usd",
    "customer": "cus_xxxxx",
    "description": "Payment for invoice 1D1C1268-0002",
    "invoice": "in_1ssss",
    "last_payment_error": {
      "charge": "ch_1Esssss",
      "code": "card_declined",
      "decline_code": "fraudulent",
      "doc_url": "https://stripe.com/docs/error-codes/card-declined",
      "message": "Your card was declined.",
      "source": {
        "id": "src_1Eapxxxx",
        "object": "source",
        "amount": null,
        "card": {
          "exp_month": 12,
          "exp_year": 2023,
          "last4": "0019",
          "country": "US",
          "brand": "Visa",
          "address_zip_check": "pass",
          "cvc_check": "pass",
          "funding": "credit",
          "fingerprint": "bMtxxxxxxxx",
          "three_d_secure": "optional",
          "name": null,
          "address_line1_check": null,
          "tokenization_method": null,
          "dynamic_last4": null
        },
        "client_secret": "src_client_secret_xxx",
        "created": 1558035311,
        "currency": null,
        "customer": "cus_F4yl2VV15h6ahh",
        "flow": "none",
        "livemode": false,
        "metadata": {
        },
        "statement_descriptor": null,
        "status": "chargeable",
        "type": "card",
        "usage": "reusable"
      },
      "type": "card_error"
    },
    "source": null,
    "statement_descriptor": null,
    "status": "requires_payment_method",
    "transfer_data": null,
    "transfer_group": null
  }
}`

**Comment by marty331** [comment]
Failure Code and Failure Message have been added to the returned data for both /customer/{uid}/subscriptions and /customer/{uid} routes.

`{
    "cancel_at_period_end": true,
    "current_period_end": 1557361022,
    "current_period_start": 1557361022,
    "end_at": 1557361022,
    "failure_code": "Card declined",
    "failure_message": "Your card was declined.",
    "nickname": "pro_basic",
    "plan_id": "pro_basic_823",
    "status": "active",
    "subscription_id": "sub_abc123"
  }`

@bbangert does this resolve this issue for you?

**Comment by bbangert** [comment]
Is that the raw failure_code that Stripe returns? We should have a specific subset of failure_code's that don't change as we'll need to add localization to them.

**Comment by bbangert** [comment]
@marty331 Did you see my question above?

**Comment by marty331** [comment]
@bbangert here is the official list of failure_codes: https://stripe.com/docs/api/payouts/failures

**Comment by lmorchard** [comment]
FWIW, we haven't actually tried using this yet, but I think this issue is probably good to be closed - `failure_code` and `failure_message` look like what we need
