### ISSUE TITLE
The payment confirmation mail is sent out even if the payment was not successful

### ISSUE THREAD

**Issue by bsurd** [mozilla/subhub#454]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Ubuntu 19.04 (x64)
- Windows 10 (x64)

#### Preconditions
- Have a FxA account without a subscriptions

#### Steps to reproduce
1. Open the [stage website](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn).
2. Click on the Subscribe Now button and complete the subscription process using a credit card number outside of the US. (eg. 6200-0000-0000-0005)

#### Expected result:
- The payment is declined, no subscription is created and no mail is sent out.

#### Actual result:
- The payment appears to be blocked in the Stripe Dashboard and is indeed declined, but a payment confirmation mail is sent, this could confuse users into thinking they have indeed made a subscription and that they were charged.

![image](https://user-images.githubusercontent.com/17178945/73540359-61546680-4438-11ea-99bc-decbd1e0ee2a.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1010)
┆Issue Number: FXA-1010

**Comment by marty331** [comment]
@bsurd I believe this was tested prior to SubHub being updated.  I just tested and did not get the corresponding email that is reported.  Could you please retest?

**Comment by bsurd** [comment]
I've retested today, this issue is indeed no longer reproducible. Closing.
