### ISSUE TITLE
Recurrent payment emails are not sent

### ISSUE THREAD

**Issue by madalincm** [mozilla/subhub#457]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account

#### Steps to reproduce
1. Go to 123done  and create a daily subscription (using prod_FUUNYnlDso7FeB)
2. Wait 24 hours 

#### Expected result:
- The recurrent payment email is sent 

#### Actual result:
- The recurrent payment email is not sent 

#### Notes
- FxA accounts used in test: mcotetiu+sub7@mozilla.com and mcotetiu+sub6@mozilla.com
- The recurrent payments are recorded in the stripe dashboard
- This might be related to https://github.com/mozilla/fxa/issues/4048 
- We are not able to test recurrent payments using the monthly product so we are not able to confirm that this happening for those also.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1043)
┆Issue Number: FXA-1043

**Comment by clouserw** [comment]
I moved to subhub repository

**Comment by stlhood** [comment]
This is now fixed and pushed to prod-test. Please retest!

**Comment by madalincm** [comment]
Verified on Win10x64 FF72 in stage.
Issue is no longer reproducing. Closing issue and marking it as verified fixed.
![image](https://user-images.githubusercontent.com/15685441/74030155-0b8f3980-49b7-11ea-9006-3b9a4cf95607.png)
