### ISSUE TITLE
Payment confirmation email is not sent for the daily product

### ISSUE THREAD

**Issue by madalincm** [mozilla/subhub#458]
#### Affected versions:
- All Firefox

#### Affected Platforms:
- Windows 10 (64-bit)

#### Preconditions
- existent FxA account

#### Steps to reproduce
1. Go to 123done  and create a daily subscription (using prod_FUUNYnlDso7FeB)
2. Observe the received emails

#### Expected result:
- The payment confirmed email is sent.

#### Actual result:
- The payment confirmed mail is not sent.

#### Notes
This is only reproducing for the daily product. (when creating the monthly subscription from the fpn website the mail is sent)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-1031)
┆Issue Number: FXA-1031

**Comment by stlhood** [comment]
This is now fixed and pushed to prod-test. Please retest!

**Comment by madalincm** [comment]
Verified on Win10x64 FF72 in stage.
Issue is no longer reproducing. Closing issue and marking it as verified fixed.
![image](https://user-images.githubusercontent.com/15685441/74029930-7ee47b80-49b6-11ea-855c-bfc55e7167e6.png)
