### ISSUE TITLE
Ensure subscription updates follow FxA schema

### ISSUE THREAD

**Issue by ianb** [mozilla/subhub#54]
I'm not sure of the status of the feature, but this ticket is to verify the status/implementation. In FxA we are checking for incoming updates (via SQS) on subscription status, implemented in https://github.com/mozilla/fxa/pull/1122

We expect the message to match this schema: https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/subhub/updates.js#L10-L19

**Comment by lmorchard** [comment]
> We expect the message to match this schema

This issue should be the inverse and move over to FxA - i.e. FxA schema should be adjusted to match subhub. 

The schema we have there is based on earlier versions of the API YAML definition and will need updating. That's part of what I'm up to this week in https://github.com/mozilla/fxa/issues/719

**Comment by marty331** [comment]
This feature is currently being worked on in Jira item SS-145, therefore I will close this issue.
