### ISSUE TITLE
subscribe_to_plan should only respond with new subscription item

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#56]
Here in [`subhub/api/payments.py`](https://github.com/mozilla/subhub/blob/master/subhub/api/payments.py#L40) the result of `stripe.Subscription.create` is discarded and the Customer is fetched to respond with the full current list of subscriptions:

```python
    stripe.Subscription.create(customer=customer.id, items=[{"plan": data["plan_id"]}])
    updated_customer = stripe.Customer.retrieve(customer.id)
    return create_return_data(updated_customer["subscriptions"]), 201
```

But, in order to create a corresponding subscription record over on FxA, it might be better to return just the new subscription details returned by `stripe.Subscription.create`.

Otherwise, we'll need to do a comparison between the subhub & FxA subscription lists for the user and add/remove based on the difference. (Of course, now that I think about it, maybe a "sync" algorithm run at significant points wouldn't be a bad idea to keep FxA consistent with subhub & stripe.)

**Comment by lmorchard** [comment]
FWIW, I also filed this issue on the FxA side - "[Implement a subscriptions sync algorithm between auth-server and subhub?](https://github.com/mozilla/fxa/issues/1148)". Maybe it *does* make sense to run a full "sync" algorithm here, rather than simply processing the addition of a new subscription when handling the result of this request.

**Comment by marty331** [comment]
Jira Issue - https://jira.mozilla.com/browse/SS-227

**Comment by jackiemunroe** [comment]
@marty331 @lmorchard It looks like the work for the JIRA ticket has been completed. Could someone verify if this issue can be closed out?

**Comment by lmorchard** [comment]
So, it looks like the implementation now literally looks for the newest subscription by date.

But, I guess I expected it to just use the return value from `stripe.Subscription.create`. If I'm reading [the API docs right](https://stripe.com/docs/api/subscriptions/create?lang=python), that will be the new subscription that just got created.

Is there a reason why we discard that return value and instead fetch the customer to look up subscriptions there?

**Comment by marty331** [comment]
@lmorchard The reason the data from stripe.Subscription.create is not used is that it does not contain all of the data elements that are required in the return values.
