### ISSUE TITLE
`doit local` fails on tests when using a personal stripe API key

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#59]
Looks like [we added tests](https://github.com/mozilla/subhub/commit/9983375f4ca486ef8075818709acd1f8f3493421#diff-5ddda38bd048b0606552d6c1890f9259R319) as a prerequisite to starting up the local server. 

But, when I run it locally with my own personal Stripe key to play with the admin panel, those tests fail. 

So, I can't start the local server unless I comment out that pre-req in `dodo.py`

**Comment by lmorchard** [comment]
From Slack:
> you can use `SKIP_TESTS=yes` to avoid running tests on `doit local`

This does fix my immediate issue, FWIW. `SKIP_TESTS=yes doit local` fires up the server for me.

**Comment by sidler-mozilla** [comment]
Would we like to close the issue as resolved, or would you prefer the I remove the `test` dep for `local`?

**Comment by lmorchard** [comment]
I'd personally be fine with closing this, since SKIP_TESTS does what I need. I think the larger issue might be mocking out requests to Stripe, but that's a much bigger thing
