### ISSUE TITLE
Inconsistencies between `nickname` vs `plan_name` and `product_name` in API schemas

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#60]
The [Plan schema in YAML](https://github.com/mozilla/subhub/blob/master/subhub/subhub_api.yaml#L310) specifies a `nickname` property. But, the [API implementation of GET `/plans`](https://github.com/mozilla/subhub/blob/master/subhub/api/payments.py#L73) uses `plan_name` and `product_name` instead.

Also, [the Subscriptions schema](https://github.com/mozilla/subhub/blob/master/subhub/subhub_api.yaml#L324) and API implementation for customer data still uses `nickname` for the Plan nickname.

Could we get all the above (i.e. Plan, Subscription, and Customer schemas) to consistently use `plan_name` and `product_name`?

**Comment by sidler-mozilla** [comment]
Agreed

**Comment by marty331** [comment]
Jira Issue - https://jira.mozilla.com/browse/SS-228

**Comment by jackiemunroe** [comment]
Resolved with: https://github.com/mozilla/subhub/pull/82

**Comment by lmorchard** [comment]
Partly resolved, IMO: `nickname` is renamed to `plan_name`, but the [Plan schema in YAML](https://github.com/mozilla/subhub/blob/3214ebec98218d7e1f35c498582ce0020da73078/subhub/subhub_api.yaml#L348) is missing `product_name` that's [implemented in the API](https://github.com/mozilla/subhub/blob/3214ebec98218d7e1f35c498582ce0020da73078/subhub/api/payments.py#L97).

**Comment by jackiemunroe** [comment]
@lmorchard Good catch! I will see about making the additional update as soon as I get a chance :)

**Comment by jackiemunroe** [comment]
@lmorchard this has been updated with https://github.com/mozilla/subhub/pull/88
