### ISSUE TITLE
Need a DELETE /customer/{uid} API resource?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#61]
This might be an edge case, but:

Over in FxA, [we cancel all subscriptions when a user is deleted](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/routes/account.js#L1249). But, we can't actually delete the customer record in subhub.

So, if someone signs up again on FxA with the same email address, subhub & Stripe still retain the old customer UID and attempts to subscribe from the new account will fail.

I think we'd need to delete the customer upon deleting the FxA account. (Also guessing if we did that, we wouldn't need to cancel the subscriptions separately.)

**Comment by marty331** [comment]
Jira Issue - https://jira.mozilla.com/browse/SS-229

**Comment by marty331** [comment]
Resolved with PR
https://github.com/mozilla/subhub/pull/132
