### ISSUE TITLE
Missing `cancel_at_period_end` property in subscriptions listed for customer

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#67]
From [the YAML](https://github.com/mozilla/subhub/blob/master/subhub/subhub_api.yaml#L247), it looks like `GET /customer/{uid}` should include `cancel_at_period_end` in the listed subscriptions. This property is missing from [the implementation](https://github.com/mozilla/subhub/blob/master/subhub/api/payments.py#L242), though.

**Comment by marty331** [comment]
Jira Issue - https://jira.mozilla.com/browse/SS-230

**Comment by jackiemunroe** [comment]
@lmorchard the JIRA ticket has been marked as done. Please verify this can be closed out.

**Comment by lmorchard** [comment]
Looks like this property is appearing now! But, it seems strange that it's giving a 201 Created response for `GET /customer/{uid}/subscriptions` - maybe that's a separate issue?
```
➜  subhub git:(master) ✗ curl -sD - -X GET --header 'Accept: application/json' --header 'Authorization: abcde' 'http://127.0.0.1:8012/v1/customer/9f960ea24a194d67ad62ee57faeb1308/subscriptions'
HTTP/1.0 201 CREATED
Content-Type: application/json
Content-Length: 337
Access-Control-Allow-Origin: *
Server: Werkzeug/0.15.2 Python/3.7.1
Date: Tue, 11 Jun 2019 22:09:21 GMT

{
  "subscriptions": [
    {
      "cancel_at_period_end": true,
      "current_period_end": 1562882826,
      "current_period_start": 1560290826,
      "ended_at": null,
      "plan_id": "plan_F4bof27uz71Vk7",
      "plan_name": "123Done Pro Monthly",
      "status": "active",
      "subscription_id": "sub_FEleCnZNUg1ZDb"
    }
  ]
}
```

**Comment by jackiemunroe** [comment]
@lmorchard I'm going to go ahead and close out this issue since it has been resolved. I do believe that should be a 200 instead of a 201. I will create a new issue for this. Thanks!
