### ISSUE TITLE
Need a way to reactivate a cancelled subscription

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#68]
Now that we have [a way to cancel a subscription at period end](https://github.com/mozilla/subhub/commit/8e9814b3d5864eb6755be08fcbde327d4b85421b), we also need a way to reactivate a subscription that's been cancelled but hasn't yet ended.

Related: https://github.com/mozilla/fxa/issues/981

**Comment by marty331** [comment]
Jira Issue - https://jira.mozilla.com/browse/SS-231

**Comment by jackiemunroe** [comment]
This feature is now in master
