### ISSUE TITLE
Add more detailed properties to error responses for Stripe errors?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#70]
When I submit a [known bad card](https://stripe.com/docs/testing#cards-responses) to update payment for a customer, we get a response with a generic error like so:
```json
{"message": "Request req_igSOxiiS3X3LWv: Your card has insufficient funds."}
```
We'd like to display some more tailored messages to the end-user and parsing this message for what happened may be difficult.

Could we maybe get some additional [Stripe API error properties](https://stripe.com/docs/api/errors) like `type`, `code`, `decline_code`, and `message` passed along in the subhub error response?

**Comment by marty331** [comment]
I have linked this issue to Jira Item: https://jira.mozilla.com/browse/SS-226 as well as #49 to make sure all aspects are covered.

**Comment by jackiemunroe** [comment]
This has been updated with: https://github.com/mozilla/subhub/pull/81
