### ISSUE TITLE
cannot use mutable object (dict) in keyword arguments

### ISSUE THREAD

**Issue by sidler-mozilla** [mozilla/subhub#92]
https://github.com/mozilla/subhub/blob/master/subhub/tests/unit/stripe/utils.py#L17-L22

Setting arguments using mutable default value is a bug:
https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html

**Comment by marty331** [comment]
subhub.test.unit.strip.utils should be refactored ln 30 & 33
